#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from runtest import cli, get_filter, run, version_info  # isort:skip
from runtest_config import configure  # isort:skip

assert version_info.major == 2

f = [
    get_filter(string='pi', rel_tolerance=1.0e-6),
]

options = cli()

ierr = 0
ierr += run(options, configure, input_files='pi.inp', filters={'stdout': f})

sys.exit(ierr)
